title: ASI-408 Interim Report 
description: This is the Interim Report for the ASI-408 Galassia-5 Mechanical Subteam for CDE4301 (2026).
theme: just-the-docs
baseurl: "/cde4301-interim-report"
url: "https://asi408-2026.github.io"
repository: asi408-2026/interim-draft-1

color_scheme: dark

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/favicon.ico"

defaults:
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "default"

# Aux links for the upper right navigation
aux_links:
  "GitHub Repo":
    - "//github.com/asi408-2026"
    

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust
# markup / liquid-based content.
footer_content: "Copyright &copy; 2025-2026 Galassia-5 Satellite Programme"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%e %b %Y" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

callouts:
  warning:
    title: Warning
    color: red
